[tool.poetry]
name = "basket_stats"
version = "0.1.0"
description = "Captation vidéo et statistiques basket – socle monorepo."
authors = ["Benoît Bolivard <you@example.com>"]
packages = [{ include = "backend" }, { include = "vision" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.14"
uvicorn = "^0.35.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
httpx = "^0.27.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
